.PHONY : 
all : Ar.svg He.svg H.svg Ne.svg Hg.svg

Ar.svg : Ar.gpi
	gnuplot $^

He.svg : He.gpi
	gnuplot $^

H.svg : H.gpi
	gnuplot $^

Ne.svg : Ne.gpi
	gnuplot $^

Hg.svg : Hg.gpi
	gnuplot $^

.PHONY : 
clean : 
	rm -f *.svg
